name: Build and push image to Docker Hub
on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo ${{github.ref_name}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          # Building on GitHub Actions is very slow, so linux/amd64 will be built on Docker Hub
          # https://github.com/shin1x1/docker-php-dev/runs/4492246209
          #platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          push: true
          tags: shin1x1/php-dev:${{github.ref_name}}